# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='status',
            field=models.CharField(default='Ended', max_length=25),
        ),
        migrations.AlterField(
            model_name='championship',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
    ]
